services:
  jekyll:
    image: ruby:3.1-alpine
    volumes:
      - .:/site
    ports:
      - "4000:4000"
      - "35729:35729"
    working_dir: /site
    entrypoint: >
      /bin/sh -c "
      apk add --no-cache build-base git &&
      gem install jekyll bundler &&
      bundle install &&
      bundle exec jekyll serve --host 0.0.0.0 --livereload --livereload-port 35729 --future"